[package]
name = "concord-client-py"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "concord"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
concord-proto = { path = "../proto" }
